{% set name = "pytest-update-test-results" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ESSS/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 93f8349335a5a779e550dba1bebc39f08d23f011d658beb27bd0874be1bc6186

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - pytest

test:
  requires:
    - pytest
  imports:
    - pytest_update_test_results
  commands:
    - pytest --help

about:
  home: https://github.com/ESSS/pytest-update-test-results
  license: MIT
  license_file: LICENSE
  summary: Pytest plugin to update test results on a jUnit XML from previous run.

extra:
  recipe-maintainers:
    - IgorTG
    - LucasRochaAbraao
    - nicoddemus
